# Generated by Django 4.2.7 on 2023-12-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_description',
            field=models.CharField(default='0', max_length=350),
        ),
    ]
