# Generated by Django 4.2.7 on 2023-12-21 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0033_remove_filmcomment_film_remove_filmcomment_user_and_more'),
        ('user_page', '0003_userlist_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='items',
        ),
        migrations.AddField(
            model_name='rating',
            name='anime',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='animepage.anime'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='anime',
            field=models.ManyToManyField(blank=True, to='animepage.anime'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_description',
            field=models.CharField(default='Описание отсутствует', max_length=350),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='name',
            field=models.CharField(default='Неопознаный список', max_length=350),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('description', models.CharField(max_length=999)),
                ('image', models.ImageField(default='default_pfpic.png', upload_to='')),
                ('anime', models.ManyToManyField(to='animepage.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('anime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animepage.anime')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animepage.film')),
            ],
        ),
    ]
