# Generated by Django 4.2.7 on 2023-12-25 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0006_comment_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='film',
        ),
    ]
