# Generated by Django 4.2.7 on 2023-11-18 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='anime',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='animepage.anime'),
        ),
    ]
