# Generated by Django 4.2.7 on 2023-11-18 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0002_episode_anime'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=255)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animepage.anime')),
            ],
        ),
    ]
