# Generated by Django 4.2.7 on 2023-11-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0003_additionalname'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='published_on_site',
            field=models.DateField(auto_created=True, default='2023-11-19'),
        ),
        migrations.AddField(
            model_name='anime',
            name='season',
            field=models.CharField(default='Лето 2023', max_length=255),
        ),
    ]
