# Generated by Django 4.2.7 on 2023-11-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0005_alter_anime_published_on_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='status',
            field=models.CharField(default='Онгоинг', max_length=100),
        ),
    ]
