# Generated by Django 4.2.7 on 2023-11-20 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0006_anime_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='file',
        ),
        migrations.AddField(
            model_name='anime',
            name='connected_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='animepage.anime'),
        ),
        migrations.AddField(
            model_name='episode',
            name='link',
            field=models.CharField(default=0, max_length=999),
        ),
    ]
