# Generated by Django 4.2.7 on 2023-11-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0007_remove_episode_file_anime_connected_with_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='connected_with',
        ),
    ]
