# Generated by Django 4.2.7 on 2023-11-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0008_remove_anime_connected_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='anime',
            name='season',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
