# Generated by Django 4.2.7 on 2023-11-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0009_anime_studio_alter_anime_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='genres/'),
        ),
    ]
