# Generated by Django 4.2.7 on 2023-11-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0011_anime_anime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='n_episode',
            field=models.IntegerField(default=1),
        ),
    ]
