# Generated by Django 4.2.7 on 2023-11-20 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0013_rename_link_episode_anilibria_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='anilibria_link',
        ),
    ]
