# Generated by Django 4.2.7 on 2023-11-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0014_remove_episode_anilibria_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='season',
        ),
        migrations.AlterField(
            model_name='anime',
            name='amount_of_episodes',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
