# Generated by Django 4.2.7 on 2023-11-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0015_remove_anime_season_alter_anime_amount_of_episodes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='date_publised',
            new_name='date_published',
        ),
    ]
