# Generated by Django 4.2.7 on 2023-11-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0017_anime_duration_anime_origin_sourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='origin_sourse',
            new_name='origin_source',
        ),
    ]
