# Generated by Django 4.2.7 on 2023-11-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0018_rename_origin_sourse_anime_origin_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_on_site', models.DateField(auto_created=True, default='2023-11-19')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('anime_type', models.CharField(max_length=255)),
                ('origin_source', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=999)),
                ('duration', models.CharField(max_length=255)),
                ('date_published', models.CharField(max_length=255)),
                ('studio', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('genres', models.ManyToManyField(to='animepage.genre')),
            ],
        ),
    ]
