# Generated by Django 4.2.7 on 2023-11-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0019_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='published_on_site',
            field=models.DateTimeField(auto_created=True, default='2023-11-19'),
        ),
        migrations.AlterField(
            model_name='film',
            name='published_on_site',
            field=models.DateTimeField(auto_created=True, default='2023-11-19'),
        ),
    ]
