# Generated by Django 4.2.7 on 2023-11-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0020_alter_anime_published_on_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='published_on_site',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='published_on_site',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
