# Generated by Django 4.2.7 on 2023-11-27 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0021_alter_anime_published_on_site_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='published_on_site',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='published_on_site',
            new_name='created_at',
        ),
    ]
