# Generated by Django 4.2.7 on 2023-11-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0023_anime_temp_type_film_temp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='anilibria_player',
            field=models.CharField(default=0, max_length=225),
        ),
    ]
