# Generated by Django 4.2.7 on 2023-12-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0025_alter_anime_date_published_alter_anime_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
