# Generated by Django 4.2.7 on 2023-12-07 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0026_alter_anime_description_alter_film_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('anime', models.ForeignKey(default='/', on_delete=django.db.models.deletion.CASCADE, to='animepage.anime')),
            ],
        ),
    ]
