# Generated by Django 4.2.7 on 2023-12-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0029_alter_additionalimage_anime_alter_anime_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalname',
            old_name='title',
            new_name='anime',
        ),
        migrations.RenameField(
            model_name='additionalname',
            old_name='title_name',
            new_name='name',
        ),
    ]
