# Generated by Django 4.2.7 on 2023-12-21 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0032_filmcomment_animecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmcomment',
            name='film',
        ),
        migrations.RemoveField(
            model_name='filmcomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='AnimeComment',
        ),
        migrations.DeleteModel(
            name='FilmComment',
        ),
    ]
