# Generated by Django 4.2.7 on 2023-12-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animepage', '0035_alter_anime_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(default=0, max_length=999),
        ),
        migrations.AlterField(
            model_name='anime',
            name='player',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
